runtime: python
env: flex

runtime_config:
    python_version: 3

resources:
    cpu: 1
    memory_gb: 6
    disk_size_gb: 10
                             
entrypoint: gunicorn -b :$PORT app:app

env_variables:
  PKL_BUCKET:  'ntu-findit-obr.appspot.com'
